[package]
name = "subway_map"
version = "0.1.0"
authors = ["Emily Crandall Fleischman <emilycf@mit.edu>"]
edition = "2018"

[dependencies]
regex-syntax = "0.6.3"
failure = "0.1.3"
failure_derive = "0.1.3"
